"""empty message

Revision ID: 368041d076cb
Revises: 596bf2993292
Create Date: 2021-07-17 15:18:54.106594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368041d076cb'
down_revision = '596bf2993292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('planet', table_name='people')
    op.drop_index('planet_2', table_name='people')
    op.drop_column('people', 'planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planet', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('planet_2', 'people', ['planet'], unique=False)
    op.create_index('planet', 'people', ['planet'], unique=False)
    # ### end Alembic commands ###
