"""empty message

Revision ID: 42016bdd6575
Revises: 368041d076cb
Create Date: 2021-07-17 16:03:43.017238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42016bdd6575'
down_revision = '368041d076cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'density')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('density', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
